version: "3.8"

services:
  couchdb:
    image: couchdb:3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdata:/opt/couchdb/data
    restart: unless-stopped
  # api:
  #   build: ./api
  #   container_name: api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - COUCHDB_URL=http://admin:admin@couchdb:5984
  #   depends_on:
  #     - couchdb
  #   restart: unless-stopped

volumes:
  couchdata:
