name: Saudações!

on:
  push:
    branches:
      - main 

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Olá
        run: echo "👋 Saudações Corinthianas!"